language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false

node_js:
  - '8'
script:
  - npm run build
  - npm run test

branches:
  except:
    - /^(v\d+\.\d+\.\d+|gh-pages)$/
